version: '3'
services:
  db:
    restart: always
    image: postgres
    volumes:
    - ./data/pg/:var/lib/postgresql/data
    expose:
    - "5432"
  job:
    restart: always
    build: .
    ports:
    - "8000:8000"
    depends_on:
    - db
    links:
    - db
    command: bash -c "scrapy crawl job"
